version: "3.8"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    links:
      - php-fpm
    volumes:
      - ./www:/var/www/html/m2:delegated
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: m2-sample-nginx
  php-fpm:
    build: ./php-fpm
    links:
      - mysql
      - redis
    volumes:
      - ./www:/var/www/html/m2:delegated
      - ./.env:/var/www/html/.env
#      - ~/.cache/composer:/home/docker/.cache/composer
#      - ~/.config/composer:/home/docker/.config/composer
    container_name: m2-sample-php-fpm
    environment:
      PHP_IDE_CONFIG: "serverName="
      XDEBUG_ENABLE: "false"
      XDEBUG_REMOTE_HOST:
#      COMPOSER_CACHE_DIR: '/home/docker/.cache/composer'
#      COMPOSER_HOME: '/home/docker/.config/composer'
  mysql:
    image: percona:5.7
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - m2-sample-mysql:/var/lib/mysql
    container_name: m2-sample-mysql
  redis:
    build: ./redis
    expose:
      - "6379"
    container_name: m2-sample-redis
#  mysql-integration-tests:
#    image: percona:5.7
#    expose:
#      - "3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=m2
#    tmpfs:
#      - /var/lib/mysql/:rw,noexec,nosuid,size=600m
#      - /tmp/:rw,noexec,nosuid,size=50m
#    container_name: m2-sample-mysql-integration-tests
volumes:
  m2-sample-mysql:
