version: "3.2"
services:
  nginx:
    image: nginx
    ports:
      - "80:8080"
    links:
      - php-fpm
    volumes:
      - type: volume
        source: ./www
        target: /var/www/html/m2
        consistent: delegated
      - ./nginx/m2.conf:/etc/nginx/conf.d/default.conf
    container_name: nginx
  php-fpm:
    build: ./php-fpm
    ports:
      - "9000:9000"
    links:
      - mysql
      - redis
    volumes:
      - type: volume
        source: ./www
        target: /var/www/html/m2
        consistent: delegated
      - ./.env:/var/www/html/.env
    container_name: php-fpm
  mysql:
    build: ./mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    container_name: mysql
  redis:
    build: ./redis
    expose:
      - "6379"
    container_name: redis
volumes:
  mysql: