version: "3.7"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on: [fpm]
    volumes:
      - ./www:/var/www/html/m2:delegated
      - ./nginx/templates:/etc/nginx/templates:delegated
    env_file:
      - .env
  fpm:
    build: ./fpm
    depends_on: [mysql, redis, elasticsearch]
    volumes:
      - ./www:/var/www/html/m2:delegated
      - ./.env:/var/www/html/.env
#      - ~/.cache/composer:/home/docker/.cache/composer:delegated
    env_file:
      - .env
  mysql:
    image: percona:5.7
    env_file:
      - .env
    ports:
      - "3306:3306"
    command: ["mysqld", "--innodb-buffer-pool-size=2048M"]
  redis:
    image: redis
    expose:
      - "6379"
    command: redis-server --bind 0.0.0.0 --maxmemory 512mb --maxmemory-policy volatile-lru --appendonly yes
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    ports:
      - "9200:9200"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
#  mysql-integration-tests:
#    image: mysql:5.7
#    expose:
#      - "3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=123123q
#      - MYSQL_DATABASE=magento_integration_tests
#    tmpfs:
#      - /var/lib/mysql/:rw,noexec,nosuid,size=600m
#      - /tmp/:rw,noexec,nosuid,size=50m
#  rabbitmq:
#    image: rabbitmq:3.7-management
#    environment:
#      RABBITMQ_DEFAULT_USER: "guest"
#      RABBITMQ_DEFAULT_PASS: "guest"
#    expose:
#      - "5672"
