version: "3.2"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    links:
      - php-fpm
    volumes:
      - ./www:/var/www/html/m2:delegated
      - ./nginx/m2.conf:/etc/nginx/conf.d/default.conf
    container_name: nginx
  php-fpm:
    build: ./php-fpm
    links:
      - mysql
      - redis
    volumes:
      - ./www:/var/www/html/m2:delegated
      - ./.env:/var/www/html/.env
    container_name: php-fpm
    environment:
      PHP_IDE_CONFIG: "serverName="
      XDEBUG_ENABLE: "false"
      XDEBUG_REMOTE_HOST:
  mysql:
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/my.cnf /etc/alternatives/my.cnf
      - mysql:/var/lib/mysql
    container_name: mysql
  redis:
    build: ./redis
    expose:
      - "6379"
    container_name: redis
volumes:
  mysql: